name: CI

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      branch:
        description: "(Optional) Branch to checkout"
        required: false
        type: string
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  path-filter:
    name: Filter Paths
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filter.outputs.python }}
      frontend: ${{ steps.filter.outputs.frontend }}
      docs: ${{ steps.filter.outputs.docs }}
      tests: ${{ steps.filter.outputs.tests }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch || github.ref }}
    - name: Filter Paths
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          python:
            - "src/backend/**"
            - "src/backend/**.py"
            - "pyproject.toml"
            - "poetry.lock"
            - "**/python_test.yml"
          tests:
            - "tests/**"
            - "src/frontend/tests/**"
          frontend:
            - "src/frontend/**"
            - "**/typescript_test.yml"
          docs:
            - "docs/**"

  test-backend:
    name: Run Backend Tests
    if: ${{ needs.path-filter.outputs.python == 'true' || needs.path-filter.outputs.tests == 'true' }}
    uses: ./.github/workflows/python_test.yml

  test-frontend:
    name: Run Frontend Tests
    if: ${{ needs.path-filter.outputs.python == 'true' || needs.path-filter.outputs.frontend == 'true' || needs.path-filter.outputs.tests == 'true' }}
    uses: ./.github/workflows/typescript_test.yml

  lint-backend:
    name: Lint Backend
    if: ${{ needs.path-filter.outputs.python == 'true' || needs.path-filter.outputs.tests == 'true' }}
    uses: ./.github/workflows/lint-py.yml

  test-docs-build:
    name: Test Docs Build
    if: ${{ needs.path-filter.outputs.docs == 'true' }}
    uses: ./.github/workflows/docs_test.yml

  ci_success:
    name: "CI Success"
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: "Check Backend Tests"
      id: backend_status
      run: |
        if [[ "$(jobs.test-backend.result)" == "failure" ]]; then
          echo "Backend tests failed"
          exit 1
        elif [[ "$(jobs.test-backend.result)" == "cancelled" ]]; then
          echo "Backend tests were cancelled"
          exit 1
        else
          echo "Backend tests passed or were skipped"
        fi
    - name: "Check Frontend Tests"
      id: frontend_status
      run: |
        if [[ "$(jobs.test-frontend.result)" == "failure" ]]; then
          echo "Frontend tests failed"
          exit 1
        elif [[ "$(jobs.test-frontend.result)" == "cancelled" ]]; then
          echo "Frontend tests were cancelled"
          exit 1
        else
          echo "Frontend tests passed or were skipped"
        fi
    - name: "Check Backend Lint"
      id: lint_status
      run: |
        if [[ "$(jobs.lint-backend.result)" == "failure" ]]; then
          echo "Backend lint failed"
          exit 1
        elif [[ "$(jobs.lint-backend.result)" == "cancelled" ]]; then
          echo "Backend lint was cancelled"
          exit 1
        else
          echo "Backend lint passed or was skipped"
        fi
    - name: "Check Docs Build"
      id: docs_status
      run: |
        if [[ "$(jobs.test-docs-build.result)" == "failure" ]]; then
          echo "Docs build failed"
          exit 1
        elif [[ "$(jobs.test-docs-build.result)" == "cancelled" ]]; then
          echo "Docs build was cancelled"
          exit 1
        else
          echo "Docs build passed or was skipped"
        fi
    - name: "CI Success"
      run: echo "All checks passed or were skipped"
