# Warning, do not check out untrusted code with
# the pull_request_target event.
name: Label PRs with Conventional Commits
on:
  pull_request_target:
    types: [ opened, edited , synchronize]

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    outputs:
      validate_output: ${{ steps.validate.outputs }}
    steps:
      - name: Validate the pull request
        id: validate
        uses: Namchee/conventional-pr@v0.15.4
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true
  label:
    needs: validate-pr
    name: Label PR
    runs-on: ubuntu-latest
    name: Lint PR
    steps:
      - name: label
        uses: action-runner/conventional-labeler@2.0.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
