# Warning, do not check out untrusted code with
# the pull_request_target event.
name: Label PRs with Conventional Commits
on:
  pull_request_target:
    types: [ opened, edited ]

jobs:
  label:
    runs-on: ubuntu-latest
    name: Lint PR
    steps:
      - name: label
        uses: action-runner/conventional-labeler@v1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
