name: Run frontend tests

on:
  pull_request:
    paths:
      - "src/frontend/**"
env:
  POETRY_VERSION: "1.8.2"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install Node.js dependencies
        run: |
          cd src/frontend
          npm ci

      # Added step to install Poetry
      - name: Install poetry
        run: pipx install poetry==$POETRY_VERSION

      # Added step to set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Specify your Python version
          cache: "poetry"

      # Assuming you have Python dependencies to install via Poetry
      - name: Install Python dependencies
        run: |
          poetry install

      # Running tests as before

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: |
          cd src/frontend
          npx playwright test --reporter=list

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: src/frontend/playwright-report/
          retention-days: 15
