name: Run frontend tests

on:
  pull_request:
    paths:
      - "src/frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Install Node.js dependencies
        run: |
          cd src/frontend
          npm ci

      # Added step to set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify your Python version

      # Added step to install Poetry
      - name: Install Poetry
        run: |
          pipx install poetry

      # Ensuring the Poetry bin directory is in PATH
      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      # Assuming you have Python dependencies to install via Poetry
      - name: Install Python dependencies
        run: |
          poetry install

      # Running tests as before
      - name: Run tests
        run: |
          cd src/frontend
          chmod +x run-tests.sh
          ./run-tests.sh
